# SPDX-License-Identifier: Apache-2.0
"""baseline schema

Revision ID: 978289c94610
Revises: 
Create Date: 2026-06-15 06:51:17.990319
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '978289c94610'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('signing_key_hex', sa.String(length=64), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('fw_version', sa.String(length=32), nullable=True),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.Column('pass_nft_id', sa.String(length=128), nullable=True),
    sa.Column('pass_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reading_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('seasons',
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('block_height_start', sa.Integer(), nullable=True),
    sa.Column('block_height_end', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('season_number')
    )
    op.create_table('attestations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('hours_online', sa.Integer(), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('oracle_sig', sa.String(length=128), nullable=True),
    sa.Column('dl_tx_id', sa.String(length=128), nullable=True),
    sa.Column('dl_key_hex', sa.String(length=256), nullable=True),
    sa.Column('block_height_at_write', sa.Integer(), nullable=True),
    sa.Column('written_to_datalayer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.ForeignKeyConstraint(['season_number'], ['seasons.season_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'season_number', name='uq_attest_node_season')
    )
    with op.batch_alter_table('attestations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attestations_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attestations_season_number'), ['season_number'], unique=False)

    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tree_ts_ms', sa.Integer(), nullable=True),
    sa.Column('fw_version', sa.String(length=32), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lon', sa.Float(), nullable=True),
    sa.Column('gps_fix', sa.Boolean(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('sig_hex', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readings_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_readings_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_readings_sig_hex'), ['sig_hex'], unique=False)

    op.create_table('uptime_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('hour_utc', sa.String(length=13), nullable=False),
    sa.Column('reading_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.node_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'hour_utc', name='uq_uptime_node_hour')
    )
    with op.batch_alter_table('uptime_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uptime_hours_hour_utc'), ['hour_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_uptime_hours_node_id'), ['node_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uptime_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uptime_hours_node_id'))
        batch_op.drop_index(batch_op.f('ix_uptime_hours_hour_utc'))

    op.drop_table('uptime_hours')
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readings_sig_hex'))
        batch_op.drop_index(batch_op.f('ix_readings_received_at'))
        batch_op.drop_index(batch_op.f('ix_readings_node_id'))

    op.drop_table('readings')
    with op.batch_alter_table('attestations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attestations_season_number'))
        batch_op.drop_index(batch_op.f('ix_attestations_node_id'))

    op.drop_table('attestations')
    op.drop_table('seasons')
    op.drop_table('nodes')
    # ### end Alembic commands ###
