# SPDX-License-Identifier: Apache-2.0
"""add readings.schema_version (T14)

Revision ID: a002d3715ffb
Revises: 03f4c36f5eb6
Create Date: 2026-06-15 08:54:36.922673
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a002d3715ffb'
down_revision: str | None = '03f4c36f5eb6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schema_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_column('schema_version')

    # ### end Alembic commands ###
