# SPDX-License-Identifier: Apache-2.0
"""The Alembic baseline must stay faithful to the models.

`alembic upgrade head` on an empty DB has to (a) create every table the ORM
declares and (b) leave NO autogenerate diff — i.e. the migrations fully
describe `Base.metadata`. If someone adds a model column without a matching
migration, `alembic check` here fails. Also asserts the migrated schema
matches what `create_all()` builds, so a `create_all`'d DB can be safely
`alembic stamp`'d.
"""
from __future__ import annotations

import os
from pathlib import Path

os.environ["ORCHARD_ORACLE_DB_URL"] = "sqlite:///:memory:"

from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect

from oracle.app import models  # noqa: F401 — populate Base.metadata
from oracle.app.config import reset_settings_for_tests
from oracle.app.db import Base, create_all, reset_for_tests

REPO = Path(__file__).resolve().parents[2]


def _cfg() -> Config:
    cfg = Config(str(REPO / "alembic.ini"))
    cfg.set_main_option("script_location", str(REPO / "oracle" / "migrations"))
    return cfg


def test_baseline_creates_all_model_tables(tmp_path, monkeypatch):
    db = tmp_path / "upgrade.db"
    monkeypatch.setenv("ORCHARD_ORACLE_DB_URL", f"sqlite:///{db.as_posix()}")
    reset_settings_for_tests()
    reset_for_tests()

    command.upgrade(_cfg(), "head")

    insp = inspect(create_engine(f"sqlite:///{db.as_posix()}"))
    tables = set(insp.get_table_names())
    assert set(Base.metadata.tables).issubset(tables), (
        f"missing {set(Base.metadata.tables) - tables}")
    assert "alembic_version" in tables  # DB is now under Alembic control


def test_no_autogenerate_drift_against_models(tmp_path, monkeypatch):
    db = tmp_path / "drift.db"
    monkeypatch.setenv("ORCHARD_ORACLE_DB_URL", f"sqlite:///{db.as_posix()}")
    reset_settings_for_tests()
    reset_for_tests()

    cfg = _cfg()
    command.upgrade(cfg, "head")
    # Raises AutogenerateDiffsDetected if the models and migrations disagree.
    command.check(cfg)


def test_migrated_schema_matches_create_all(tmp_path, monkeypatch):
    mig = tmp_path / "mig.db"
    monkeypatch.setenv("ORCHARD_ORACLE_DB_URL", f"sqlite:///{mig.as_posix()}")
    reset_settings_for_tests()
    reset_for_tests()
    command.upgrade(_cfg(), "head")
    mig_cols = _columns(f"sqlite:///{mig.as_posix()}")

    ca = tmp_path / "ca.db"
    monkeypatch.setenv("ORCHARD_ORACLE_DB_URL", f"sqlite:///{ca.as_posix()}")
    reset_settings_for_tests()
    reset_for_tests()
    create_all()
    ca_cols = _columns(f"sqlite:///{ca.as_posix()}")

    assert mig_cols == ca_cols


def _columns(url: str) -> dict[str, set[str]]:
    insp = inspect(create_engine(url))
    return {
        t: {c["name"] for c in insp.get_columns(t)}
        for t in insp.get_table_names()
        if t != "alembic_version"
    }
